#baseurl = "http://localhost:1313"
baseurl = "https://linuxlemming.com"
#baseurl = "https://rastacalavera.gitlab.io/linuxlemming/"
canonifyURLs = true
#relativeURLs = true
languageCode = "en-us"
title = "The Linux Lemming"
theme = ["castanet"]
googleAnalytics = ""
paginate = "9"
buildFuture = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[permalinks]
  page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one sub-menu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "About"
    #identifier = "about"
    url = "/TLL"

#[[Menu.Main]]
 #   name = "Contact"
 #   identifier = "contact"
 #   url = "/contact"

[[Menu.Main]]
    name = "Host"
    identifier = "host"
    url = "/host"

[[Menu.Main]]
    name = "Guests"
    identifier = "guests"
    url = "/guest"

[[Menu.Main]]
    name = "Upcoming Episodes"
    identifier = "upcoming"
    url = "/upcoming"

[[Menu.Main]]
    name = "Blog"
    identifier = "blog"
    url = "/blog"

[[Menu.Main]]
    name = "Resources"
    identifier = "resources"
    url = "#!"

[[Menu.Main]]
    name = "Podcasts"
    identifier = "podcasts"
    url = "/Other Podcasts"
    parent = "resources"

[[Menu.Main]]
    name = "Links"
    identifier = "links"
    url = "/Resources"
    parent = "resources"

[[Menu.Main]]
    name = "Credits"
    identifier = "credits"
    url = "/Credits"
    parent = "resources"    

[params]
mainSections = ["episode"]
#episode_number_style  = "brackets"
#episode_number_prefix = "CWC"
site_theme = "grey"
# site_layout = "grid"
site_layout = "row"
show_next_upcoming = "true"
show_live_status = "\"ended\"" #pending/live/ended
show_live_start = "2022-11-22T20:30:00-06:00" #need to convert, https://dencode.com/en/date/iso8601
show_live_end = "2022-11-22T22:00:00-06:00" #need to convert, https://dencode.com/en/date/iso8601
enable_jumbo = "true"
# enable_jumbo = "false"
# truncate = "100"
about_logo = "img/misc/calaveraLogo.png"
copyright_notice = "Copyright 2021 The Linux Lemming"
# itunes_subscribe = "https://podcasts.apple.com/us/podcast/arrested-devops/id773888088?ign-mpt=uo%3D4&mt=2"
# android_subscribe = "http://subscribeonandroid.com/feeds.podtrac.com/VGAulpN7MY1U"
# spotify_subscribe = "https://open.spotify.com/show/..."
# google_play_subscribe = "https://podcasts.google.com/feed/aHR0cHM6Ly93d3cuYXJyZXN0ZWRkZXZvcHMuY29tL2VwaXNvZGUvaW5kZXgueG1s"
# stitcher_subscribe = "http://www.stitcher.com/podcast/arrested-devops-2/arrested-devops"
# soundcloud_subscribe = "http://feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
# pocketcasts_subscribe = "http://pcasts.in/feed/feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
# mailchimp_subscribe = "//arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc"
# rss_subscribe = "http://rss.linuxlemming.com/feed.xml" #only set this if you don't want to use the built-in feed
description = "The Linux Lemming is here to help you find solid, accurate information in the self-hosting world and to improve documentation for projects as errors arise."
media_prefix = "https://linuxlemming.com/files/"
#disqusShortname = ""
  [params.feed]
    copyright = "Copyright 2021 The Linux Lemming" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "How do I get this to work?" #no markdown or HTML
    itunes_author = "Rastacalavera" #no markdown or HTML
    itunes_summary = "A show that explores the open source ecosystem and muddles through documentation. It a show that documents project documentation quality and tries to contribute back. Is that meta enough for you?" # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Rastacalavera"
    itunes_owner_email = "rastacalavera@proton.me" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on Apple Podcasts. It will not be publicly displayed on Apple Podcasts.
    itunes_image = "https://linuxlemming.com/img/LLcover.png" #fqdn to the image art for your podcast.
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Software How-To"
    itunes_second_sub_category = "Tech News"
    language = "en-us"

  [params.realfavicongenerator] # https://realfavicongenerator.net/
    mask_icon_color="#5bbad5"
    msapplication_tilecolor="#2b5797"

  [params.social]
    github = "rastacalavera/linuxlemming"
    gitlab = "rastacalavera/linuxlemming"

  [params.authors]
    [params.authors.show]
      #name	= "RastaCalavera"
      thumbnail = "img/LLcover.png" #main circle image on landing page
      #thumbnail = "/img/host/calaveraJP.jpeg" #main circle image on landing page
      bio = "A Linux enthusiast and maker at heart."
      
    #[params.authors.rastacalavera]
      #name	= "RastaCalavera"
      #thumbnail = "img/host/calaveraJP.jpeg" #main circle image on landing page
      #thumbnail = "/img/host/calaveraJP.jpeg" #main circle image on landing page
      #bio = "A Linux enthusiast and maker at heart."
      #[params.authors.rastacalavera.social]
        #github = "rastacalavera"

####
##added to try to get html to render
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
